// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: protos/PropleInfo.proto

package people

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeopleInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Hobby   string `protobuf:"bytes,3,opt,name=hobby,proto3" json:"hobby,omitempty"`
	Age     int32  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Height  int32  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Weight  int32  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PeopleInfoRequest) Reset() {
	*x = PeopleInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_PropleInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeopleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeopleInfoRequest) ProtoMessage() {}

func (x *PeopleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_PropleInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeopleInfoRequest.ProtoReflect.Descriptor instead.
func (*PeopleInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_PropleInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PeopleInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeopleInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeopleInfoRequest) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *PeopleInfoRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PeopleInfoRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PeopleInfoRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PeopleInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Errors  []*DataErrors `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *PeopleInfoResponse) Reset() {
	*x = PeopleInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_PropleInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeopleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeopleInfoResponse) ProtoMessage() {}

func (x *PeopleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_PropleInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeopleInfoResponse.ProtoReflect.Descriptor instead.
func (*PeopleInfoResponse) Descriptor() ([]byte, []int) {
	return file_protos_PropleInfo_proto_rawDescGZIP(), []int{1}
}

func (x *PeopleInfoResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PeopleInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PeopleInfoResponse) GetErrors() []*DataErrors {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DataErrors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DataErrors) Reset() {
	*x = DataErrors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_PropleInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataErrors) ProtoMessage() {}

func (x *DataErrors) ProtoReflect() protoreflect.Message {
	mi := &file_protos_PropleInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataErrors.ProtoReflect.Descriptor instead.
func (*DataErrors) Descriptor() ([]byte, []int) {
	return file_protos_PropleInfo_proto_rawDescGZIP(), []int{2}
}

func (x *DataErrors) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DataErrors) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_protos_PropleInfo_proto protoreflect.FileDescriptor

var file_protos_PropleInfo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x50, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x72, 0x0a,
	0x12, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x42, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x5c, 0x0a, 0x11, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x50, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x42, 0x2a, 0x0a, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x42, 0x0f, 0x50,
	0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_PropleInfo_proto_rawDescOnce sync.Once
	file_protos_PropleInfo_proto_rawDescData = file_protos_PropleInfo_proto_rawDesc
)

func file_protos_PropleInfo_proto_rawDescGZIP() []byte {
	file_protos_PropleInfo_proto_rawDescOnce.Do(func() {
		file_protos_PropleInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_PropleInfo_proto_rawDescData)
	})
	return file_protos_PropleInfo_proto_rawDescData
}

var file_protos_PropleInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_PropleInfo_proto_goTypes = []interface{}{
	(*PeopleInfoRequest)(nil),  // 0: people.PeopleInfoRequest
	(*PeopleInfoResponse)(nil), // 1: people.PeopleInfoResponse
	(*DataErrors)(nil),         // 2: people.DataErrors
}
var file_protos_PropleInfo_proto_depIdxs = []int32{
	2, // 0: people.PeopleInfoResponse.errors:type_name -> people.DataErrors
	0, // 1: people.PeopleInfoService.PeopleInfo:input_type -> people.PeopleInfoRequest
	1, // 2: people.PeopleInfoService.PeopleInfo:output_type -> people.PeopleInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_PropleInfo_proto_init() }
func file_protos_PropleInfo_proto_init() {
	if File_protos_PropleInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_PropleInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeopleInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_PropleInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeopleInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_PropleInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataErrors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_PropleInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_PropleInfo_proto_goTypes,
		DependencyIndexes: file_protos_PropleInfo_proto_depIdxs,
		MessageInfos:      file_protos_PropleInfo_proto_msgTypes,
	}.Build()
	File_protos_PropleInfo_proto = out.File
	file_protos_PropleInfo_proto_rawDesc = nil
	file_protos_PropleInfo_proto_goTypes = nil
	file_protos_PropleInfo_proto_depIdxs = nil
}
